; ┏━━━━━━━━━━━━━━━━┓
; ┃ 文件名   :	SE_PROC.INC	    ┃
; ┃ 版本号   :	2.0		    ┃
; ┃ 作	 者   :	简晶		    ┃
; ┃ 日	 期   :	1991 年	12 月	    ┃
; ┃				    ┃
; ┃ 版权所有 (★)Starsoft Corp,.   ┃
; ┃ Allright reserved in ShenZhen  ┃
; ┗━━━━━━━━━━━━━━━━┛
;
; 本文件包括全部应包含的共 17 个功能执行文件
; ------------------------------------------

INCLUDE	Se_Keyb.inc	;  1.键盘
INCLUDE	Se_Cros.inc	;  2.光标
INCLUDE	Se_Show.inc	;  3.显示
INCLUDE	Se_Inst.inc	;  4.插入
INCLUDE	Se_Delt.inc	;  5.删除
INCLUDE	Se_Blck.inc	;  6.块
INCLUDE	Se_Pick.inc	;  7.片
INCLUDE	Se_Find.inc	;  8.查找/替换
INCLUDE	Se_Calc.inc	;  9.计算
INCLUDE	Se_File.inc	; 10.文件
INCLUDE	Se_Erro.inc	; 11.错误
INCLUDE	Se_Othr.inc	; 13.其他
INCLUDE	Se_Wdfn.inc	; 14.控制键处理
INCLUDE	Se_Ckfn.inc	; 15.扩展键处理
INCLUDE	Se_Prin.inc	; 16.打印
INCLUDE	Se_Help.inc	; 17.帮助

